language: ruby
rvm:
  - 2.0.0
  - 2.1.0
env:
  - DB=sqlite
script:
  - RAILS_ENV=test bundle exec rake --trace db:migrate test
before_script:
  - cp test/dummy/config/database.travis.yml test/dummy/config/database.yml

